import Vue from 'vue'
import { MLInstaller, MLCreate, MLanguage } from 'vue-multilanguage'

Vue.use(MLInstaller)

export default new MLCreate({
  initial: 'en',
  save: process.env.NODE_ENV === 'production',
  languages: [
    new MLanguage('en').create({
      button_exit: 'Exit',
      button_delete: 'Delete',
      button_cancel: 'Cancel',
      button_send: 'Send',
      button_back: 'Back',
      button_add: 'Add',
      button_search: 'Search',
      button_edit: 'Edit',
      button_previous: 'Previous',
      button_next: 'Next',
      button_save: 'Save',

      weazel_addnews: 'Add news',
      weazel_title: 'Enter the title',
      weazel_subtitle: 'Enter the subtitle',
      weazel_text: 'Enter text',
      weazel_picture_link: 'Picture link',
      weazel_publish: 'Publish',
      weazel_more: 'Read more',

      police_name: '911 CALL POLICE',
      police_main_description: 'Panic Button - Police officers will receive a call from your phone number and your current position. For emergencies only!',
      police_main_sent: 'Сall has been sent',
      police_main_descriptionA: 'The nearest patrol headed to your position on high alert.',
      police_main_descriptionB: 'When police officers arrive, do not make any sudden movements, rude insults, or other actions that could mistakenly identify you as a criminal.',
      police_secondary_description: 'Briefly describe the call. The first police officer released will take care of your problem. No more than 100 characters.',
      police_button_standart: 'Regular call',
      police_call_police: 'Call the police',
      police_call_thx: 'Thank you!',
      police_call_description: 'your message has been sent',

      ambulance_name: 'Ambulance',
      ambulance_button_A: 'Emergency ambulance',
      ambulance_button_B: 'Make an appointment',
      ambulance_button_C: 'General information',
      ambulance_A_title: 'Emergency ambulance call',
      ambulance_A_description: 'Attention! You are solely responsible for false calls. Use only for emergency calls!',
      ambulance_A_call: 'Call for help',
      ambulance_A_sended_titleA: 'Please wait for the ambulance doctors.',
      ambulance_A_sended_titleB: 'If there are victims, provide first aid.',
      ambulance_B_title: 'Appointment',
      ambulance_B_name: 'First name and last name',
      ambulance_B_subject: 'Subject',
      ambulance_B_description: 'The registrar will receive your message and contact you shortly.',
      ambulance_B_sign: 'Sign up',
      ambulance_B_message_send: 'Message has been successfully sent',
      ambulance_C_title: 'Dear residents of the state!',
      ambulance_C_text: 'We are committed to preserving and promoting your health and will do everything we can to make your stay in our hospital comfortable and your recovery quicker. Our ultimate goal is to provide you with quality medical care.',

      taxi_title: 'Cab call',
      taxi_call: 'Call',
      taxi_searching: 'Searching',
      taxi_nocars: 'Unfortunately, all the cars are busy. Try again later.',

      call_keys: 'Keypad',
      call_contacts: 'Contacts',
      call_name: 'Name',
      call_number: 'Number',
      call_note: 'Note',
      call_button_call: 'Call',
      call_button_message: 'Message',
      call_button_delete: 'Delete contact',
      call_error1: 'Enter a name',
      call_error2: 'Enter the number',
      call_call: 'Calling',
      call_incoming: 'Incoming',

      youtube_title: 'Enter the link to the video',
      youtube_run: 'Run',

      messages_title: 'Messages',
      messages_write: 'Write',
      messages_newA: 'New',
      messages_new: 'New message',

      radio_all: 'All radios',

        setting_app: 'Settings',
        setting_account: 'Account',
        setting_design: 'Design',
        setting_myacoung: 'My Account',
        setting_myname: 'My name',
        setting_myphone: 'Phone number',
        setting_bgtext: 'Background image:',
        setting_helptext: '*Leave the field blank for the standard image.',

        bleeter_profile: 'Profile',
        bleeter_nickname: 'Nikcname',
        bleeter_error: 'Only Latin letters and numbers are allowed. The length is from 3 to 20 characters.',
        bleeter_bleet: 'Bleet',
        bleeter_newbleet: 'New bleet',
        bleeter_text: 'Message',
        bleeter_image: 'Image url',

        darkchat_menuA: 'Coded chat',
        darkchat_menuB: 'Anonumous feed',
        darkchat_menuC: 'Help',
        darkchat_message: 'Message',
        darkchat_recipient_code: 'Recipient code',
        darkchat_loading: 'Connecting to server',
        darkchat_helpA: 'The coded chat section: enter the code of the interlocutor and he will get your message. You will also receive all messages sent to your code.',
        darkchat_helpB: "The anonymous feed section. You will see all messages from the general chat. Everyone will see your message. No one will see the sender's address.Completely anonymous!",

        yellowpages_button: 'Place an ad',
        yellowpages_text: 'Message',
        yellowpages_image: 'Image',
        yellowpages_category: 'Category',
    }),
    new MLanguage('ru').create({
      button_exit: 'Выход',
      button_delete: 'Удалить',
      button_cancel: 'Отмена',
      button_send: 'Отправить',
      button_back: 'Назад',
      button_add: 'Добавить',
      button_search: 'Поиск',
      button_edit: 'Редактировать',
      button_previous: 'Назад',
      button_next: 'Вперед',
      button_save: 'Сохранить',

      weazel_addnews: 'Добавить новость',
      weazel_title: 'Введите заголовок',
      weazel_subtitle: 'Введите подзаголовок',
      weazel_text: 'Введите текст',
      weazel_picture_link: 'Ссылка на картинку',
      weazel_publish: 'Опубликовать',
      weazel_more: 'Подробнее',

      police_name: '911 CALL POLICE',
      police_main_description: 'Кнопка паники - сотрудники полиции получат вызов с вашего номера телефона и вашу текущую позицию. Только для экстренных случаев!',
      police_main_sent: 'Вызов отправлен!',
      police_main_descriptionA: 'Близжайший патруль направился к вашей позиции в режиме повышенной готовности.',
      police_main_descriptionB: 'При прибытии сотрудников полиции не совершайте резких движений, грубых оскорблений и других действий, которые могут ошибочно указать на вас в качестве преступника.',
      police_secondary_description: 'Кратко опишите вызов. Первый освободившийся сотрудник полиции займется вашей проблемой. Не более 100 символов.',
      police_button_standart: 'Обычный вызов',
      police_call_police: 'Вызвать полицию',
      police_call_thx: 'Спасибо!',
      police_call_description: 'Ваше сообщение отправлено!',

      ambulance_name: 'Ambulance',
      ambulance_button_A: 'Срочный вызов скорой',
      ambulance_button_B: 'Записаться на приём',
      ambulance_button_C: 'Общая информация',
      ambulance_A_title: 'Срочный вызов скорой помощи',
      ambulance_A_description: 'Внимание! Вы несете полную ответственность за ложный вызов. Используйте только для экстренных вызовов!',
      ambulance_A_call: 'Помощь вызвана',
      ambulance_A_sended_titleA: 'Пожалуйста, дождитесь врачей скорой помощи.',
      ambulance_A_sended_titleB: 'Если есть пострадавшие, окажите первую помощь.',
      ambulance_B_title: 'Запись на прием',
      ambulance_B_name: 'Имя и фамилия:',
      ambulance_B_subject: 'Тема обращения:',
      ambulance_B_description: 'Регистратор получит ваше сообщения и свяжется с вами в ближайшее время.',
      ambulance_B_sign: 'Записаться',
      ambulance_B_message_send: 'Сообщение успешно отправлено:',
      ambulance_C_title: 'Уважаемые жители штата!',
      ambulance_C_text: 'Мы стремимся к сохранению и укреплению Вашего здоровья и сделаем все, чтобы Ваше пребывание в нашей больнице стало комфортным, а выздоровление — быстрым. Наша конечная цель — предоставление Вам качественной медицинской помощи.',

      taxi_title: 'Вызов такси',
      taxi_call: 'Вызвать',
      taxi_searching: 'Поиск',
      taxi_nocars: 'К сожалению, все автомобили заняты. Попробуйте позднее.',

      call_keys: 'Клавиши',
      call_contacts: 'Контакты',
      call_name: 'Имя',
      call_number: 'Телефон',
      call_note: 'Заметка',
      call_button_call: 'Позвонить',
      call_button_message: 'Сообщение',
      call_button_delete: 'Удалить контакт',
      call_error1: 'Введите имя',
      call_error2: 'Введите номер',
      call_call: 'Звоним',
      call_incoming: 'Входящий',

      youtube_title: 'Введите ссылку на ролик',
      youtube_run: 'Запустить',

      messages_title: 'Сообщения',
      messages_write: 'Написать',
      messages_new: 'Новое сообщение',

      radio_all: 'Все радиостанции',

        setting_app: 'Настройки',
        setting_account: 'Аккаунт',
        setting_design: 'Дизайн',
        setting_myacoung: 'Мой аккаунт',
        setting_myname: 'Моё имя',
        setting_myphone: 'Мой номер',
        setting_bgtext: 'Фоновое изображение:',
        setting_helptext: '*Оставьте поле пустым для стандартного изображения.',

        bleeter_profile: 'Профиль',
        bleeter_nickname: 'Никнейм',
        bleeter_error: 'Допускаются только латинские буквы и цифры. Длина от 3 до 20 символов!',
        bleeter_bleet: 'Блитнуть',
        bleeter_newbleet: 'Новый блит',
        bleeter_text: 'Сообщение',
        bleeter_image: 'Изображение',

        darkchat_menuA: 'Coded chat',
        darkchat_menuB: 'Anonumous feed',
        darkchat_menuC: 'Help',
        darkchat_message: 'Message',
        darkchat_recipient_code: 'Recipient code',
        darkchat_loading: 'Connecting to server',
        darkchat_helpA: 'The coded chat section: enter the code of the interlocutor and he will get your message. You will also receive all messages sent to your code.',
        darkchat_helpB: "The anonymous feed section. You will see all messages from the general chat. Everyone will see your message. No one will see the sender's address.Completely anonymous!",

        yellowpages_button: 'Разместить объявление',
        yellowpages_text: 'Сообщение',
        yellowpages_image: 'Изображение',
        yellowpages_category: 'Категория',

      
    })
  ]
})
